version: '3'
services:
    programming_languages_env:
        build: ./
        image: programming_languages_image
        container_name: programming_languages_container
        tty: true
        stdin_open: true
        volumes:
          - ./:/workspace
        dns:
          - 8.8.8.8
        ports:
          - 3000:3000